language: node_js
node_js:
  - '0.10'
install:
  - npm install
  - npm install -g grunt-cli
  - npm install -g tsd
before_script:
  - grunt update
script:
  - npm test
notifications:
  email:
    recipients:
      - djbsnx@gmail.com
    on_success: change
    on_failure: always
